export enum QUERY_KEYS {
  USER_PROFILE = "USER_PROFILE",
  INVESTORS = "INVESTORS",
  INVESTOR = "INVESTOR",
  SYNDICATE_LEADERS = "SYNDICATE_LEADERS",
  SYNDICATES_FOR_LEADERS = "SYNDICATES_FOR_LEADERS",
  SYNDICATE = "SYNDICATE",
  SYNDICATE_BALANCE = "SYNDICATE_BALANCE",
  SYNDICATE_DEALS = "SYNDICATE_DEALS",
  TOTAL_TRANSACTIONS = "TOTAL_TRANSACTIONS",
  TOTAL_SYNDICATE = "TOTAL_SYNDICATE",
  TOTAL_INVESTORS = "TOTAL_INVESTORS",
}
